import type { Metadata } from 'next'

import { Navbar } from '@/components/Navbar'
import { ToastContainer } from 'react-toastify';

import '@/styles/globals.css'
import 'react-toastify/dist/ReactToastify.css';
import TopProgressbar from '@/components/Layouts/TopProgressbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`bg-primary-bg text-text-color`}>


        <video className="bg-video" src="/background.mp4" autoPlay loop muted></video>

        <TopProgressbar>
          <Navbar />

          {children}
        </TopProgressbar>
        <ToastContainer />
      </body>
    </html>
  )
}
