import type { Metadata } from 'next'

import { Navbar } from '@/components/Navbar'
import { ToastContainer } from 'react-toastify';

import '@/styles/globals.css'
import 'react-toastify/dist/ReactToastify.css';

// import '@react-pdf-viewer/core/lib/styles/index.css';
// import '@react-pdf-viewer/default-layout/lib/styles/index.css';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={`bg-primary-bg text-text-color`}>
        <video className="bg-video" src="/background.mp4" autoPlay loop muted></video>

        <Navbar />

        {children}
        <ToastContainer />
      </body>
    </html>
  )
}
